title: "HYBERFLOW"
description: Open-Source Design of a Hydraulically Actuated Bioprinthead with Flow rate Feedback Control

github_username: LnBdd
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: "theme"
